"""initial

Revision ID: 0e442c6c21db
Revises: 
Create Date: 2026-05-24 21:01:57.050760+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0e442c6c21db'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('imagen_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_codigo'), 'categorias', ['codigo'], unique=True)
    op.create_index(op.f('ix_categorias_nombre'), 'categorias', ['nombre'], unique=True)
    op.create_table('estados_pedido',
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('es_terminal', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('formas_pago',
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('habilitado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('ingredientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('es_alergeno', sa.Boolean(), nullable=False),
    sa.Column('costo', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unidad_medida', sa.Enum('KG', 'L', 'UNIDADES', name='unidadmedida'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredientes_codigo'), 'ingredientes', ['codigo'], unique=True)
    op.create_index(op.f('ix_ingredientes_nombre'), 'ingredientes', ['nombre'], unique=True)
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('imagen_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('tipo', sa.Enum('TERMINADO', 'MANUFACTURADO', name='tipoproducto'), nullable=False),
    sa.Column('unidad_medida', sa.Enum('KG', 'L', 'UNIDADES', name='unidadmedida'), nullable=False),
    sa.Column('precio_base', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_cantidad', sa.Integer(), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_codigo'), 'productos', ['codigo'], unique=True)
    op.create_index(op.f('ix_productos_nombre'), 'productos', ['nombre'], unique=True)
    op.create_table('roles',
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('codigo'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('apellido', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=254), nullable=False),
    sa.Column('celular', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('direcciones_entrega',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('alias', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('linea1', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('linea2', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('ciudad', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('provincia', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('codigo_postal', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_direcciones_entrega_usuario_id'), 'direcciones_entrega', ['usuario_id'], unique=False)
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('direccion_id', sa.Integer(), nullable=True),
    sa.Column('direccion_snapshot', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estado_codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('forma_pago_codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('costo_envio', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estado_codigo'], ['estados_pedido.codigo'], ),
    sa.ForeignKeyConstraint(['forma_pago_codigo'], ['formas_pago.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_codigo'), 'pedidos', ['codigo'], unique=True)
    op.create_index(op.f('ix_pedidos_usuario_id'), 'pedidos', ['usuario_id'], unique=False)
    op.create_table('producto_categorias',
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('producto_id', 'categoria_id')
    )
    op.create_table('producto_ingredientes',
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('ingrediente_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('es_removible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('producto_id', 'ingrediente_id')
    )
    op.create_table('usuario_roles',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol_codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('asignado_por_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asignado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['rol_codigo'], ['roles.codigo'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'rol_codigo')
    )
    op.create_table('detalle_pedidos',
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.SmallInteger(), nullable=False),
    sa.Column('nombre_snapshot', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('precio_snapshot', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal_snap', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('personalizacion', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('pedido_id', 'producto_id')
    )
    op.create_table('historial_estados_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('estado_desde', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('estado_hacia', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('motivo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['estado_desde'], ['estados_pedido.codigo'], ),
    sa.ForeignKeyConstraint(['estado_hacia'], ['estados_pedido.codigo'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_estados_pedido_pedido_id'), 'historial_estados_pedido', ['pedido_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historial_estados_pedido_pedido_id'), table_name='historial_estados_pedido')
    op.drop_table('historial_estados_pedido')
    op.drop_table('detalle_pedidos')
    op.drop_table('usuario_roles')
    op.drop_table('producto_ingredientes')
    op.drop_table('producto_categorias')
    op.drop_index(op.f('ix_pedidos_usuario_id'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_codigo'), table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_index(op.f('ix_direcciones_entrega_usuario_id'), table_name='direcciones_entrega')
    op.drop_table('direcciones_entrega')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('roles')
    op.drop_index(op.f('ix_productos_nombre'), table_name='productos')
    op.drop_index(op.f('ix_productos_codigo'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_ingredientes_nombre'), table_name='ingredientes')
    op.drop_index(op.f('ix_ingredientes_codigo'), table_name='ingredientes')
    op.drop_table('ingredientes')
    op.drop_table('formas_pago')
    op.drop_table('estados_pedido')
    op.drop_index(op.f('ix_categorias_nombre'), table_name='categorias')
    op.drop_index(op.f('ix_categorias_codigo'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
